"""modelos iniciales: scans, assets, findings

Revision ID: 50a2c71b981a
Revises: 
Create Date: 2026-09-13 15:30:45.084336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50a2c71b981a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='scanstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_domain'), 'scans', ['domain'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('ip_addresses', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('leaks_internal_addressing', sa.Boolean(), nullable=False),
    sa.Column('open_ports', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_hostname'), 'assets', ['hostname'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('finding_type', sa.String(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('unknown', 'low', 'medium', 'high', 'critical', name='findingseverity'), nullable=False),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_finding_type'), 'findings', ['finding_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_findings_finding_type'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_assets_hostname'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_scans_domain'), table_name='scans')
    op.drop_table('scans')
    # ### end Alembic commands ###
